export const numpadValues: Record<string, string> = {
  kp_divide: "/",
  kp_multiply: "*",
  kp_minus: "-",
  kp_plus: "+",
  kp_enter: "Enter",
  kp_del: ".",
  kp_0: "0",
  kp_1: "1",
  kp_2: "2",
  kp_3: "3",
  kp_4: "4",
  kp_5: "5",
  kp_6: "6",
  kp_7: "7",
  kp_8: "8",
  kp_9: "9",
};
export const midValues: Record<string, string> = {
  ins: "Ins",
  home: "Home",
  pgup: "Pg↑",
  pgdn: "Pg↓",
  del: "Del",
  end: "End",
  uparrow: "↑",
  downarrow: "↓",
  leftarrow: "←",
  rightarrow: "→",
};
export const mainValues: Record<string, string> = {
  backspace: "⌫",
  capslock: "Caps",
  ralt: "Alt",
  rctrl: "Ctrl",
  shift: "Shift",
  esc: "Esc",
  ctrl: "Ctrl",
  alt: "Alt",
  space: "Space",
  semicolon: ";",
  enter: "Enter",
  tab: "Tab",
};
